; PlatformIO Project Configuration File
;
; Build options: build flags, source filter
; Upload options: custom upload port, speed and extra flags
; Library options: dependencies, extra library storages
; Advanced options: extra scripting
;
; Docs: https://docs.platformio.org/page/projectconf.html

[env:seeed_xiao_esp32c3]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino

build_flags =
    -DAPI_HOST=\"192.168.150.2\"
    -DAPI_PORT=3000
    -DFIRMWARE_HOST=\"gym907-0001.iptime.org\"
    -DFIRMWARE_PORT=3004
    -DFIRMWARE_ID=\"0a54bc0c-630b-4235-9657-2bdfef0b23ab\"
    -DLAN_LINK_WAIT_MS=15000UL
    -DLAN_LINK_POLL_INTERVAL_MS=250UL
    -DLAN_DHCP_RETRY_COUNT=1

lib_deps =
    UIPEthernet
    bblanchon/ArduinoJson
