idf_component_register(SRCS "h264_multi_encoder.c" "main.c"
                             "app_video.c"
                             "mjpeg_recorder.c"
                             "mjpeg_spool.c"
                             "h264_encoder.c"
                             "h264_spool.c"
                             "mp4_muxer.c"
                             "sd_card.c"
                    INCLUDE_DIRS ".")