[env:seeed_xiao_esp32c3]
platform = espressif32@6.6.0
board = seeed_xiao_esp32c3
framework = arduino
build_src_filter =
  +<main.cpp>
  -<main_original.cpp>
lib_ldf_mode = deep+
lib_deps =
  ESP32Ping
  DHT sensor library
  Adafruit Unified Sensor
  ArduinoBLE
  ArduinoJson
  NTPClient
  knolleary/PubSubClient
