; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
lib_deps =
  miguelbalboa/MFRC522
build_flags =
  -std=gnu++2a
build_unflags =
  -std=gnu++20

[env:seeed_xiao_esp32c3]
extends = env
build_flags =
  ${env.build_flags}
  -DSLV_ID=1

[env:slave1]
extends = env
build_flags =
  ${env.build_flags}
  -DSLV_ID=1

[env:slave2]
extends = env
build_flags =
  ${env.build_flags}
  -DSLV_ID=2

[env:slave3]
extends = env
build_flags =
  ${env.build_flags}
  -DSLV_ID=3

[env:slave4]
extends = env
build_flags =
  ${env.build_flags}
  -DSLV_ID=4
