[platformio]
default_envs = esp32-c3-devkitm-1

[common]
custom_gdrive_copy_dir = G:/.shortcut-targets-by-id/1eOl--DT4rr56gYI69AsP3L1Eyd-glIoh/3D 프린터 사용방법 인수인계/촬영 사진 영상/강동현/Smartplug 관련 파일/smartplug 펌웨어 버전 폴더/esp8685/custom
custom_server_upload_dir = C:/WS/vs_kdh/pnk_kdh/자체제작OTA 대시보드 서버/uploads
custom_output_basename = esp8685_custom.bin
custom_remote_ota_host = gym907-0001.iptime.org
custom_remote_ota_port = 23
custom_remote_ota_user = dockeruser
custom_remote_ota_password = cyz5sXpqvJna
custom_remote_ota_dir = /home/pnkslabserver/tasmota-firmware
custom_remote_ota_subdir = esp8685/custom
custom_remote_ota_link_script = /home/pnkslabserver/tasmota-firmware/common/update_latest_links.py

[env:esp32-c3-devkitm-1]
platform = espressif32@6.13.0
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
board_build.partitions = partitions.csv
build_src_filter =
  +<*>
  -<migration_safeboot_main.cpp>
extra_scripts =
  post:pio-tools/post-firmware-copy.py
lib_deps =
  bblanchon/ArduinoJson @ ^6.21.5
  knolleary/PubSubClient @ ^2.8
  arduino-libraries/NTPClient @ ^3.2.1
  tzapu/WiFiManager @ ^2.0.17
