; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
build_dir = C:/WS/vs_kdh/pio_build/cc-retail-fittingroom_stylingbooth

[env:seeed_xiao_esp32c3]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino

monitor_filters = esp32_exception_decoder
build_flags =
    -DWIFI_SSID=\"CC-Retail\"
    -DWIFI_PASS=\"pnks1111\"
    -DAPI_HOST=\"gym907-0001.iptime.org\"
    -DAPI_PORT=3007
    -DMQTT_HOST=\"gym907-0001.iptime.org\"
    -DMQTT_PORT=1883
    -DMQTT_USER=\"pnks\"
    -DMQTT_PASS=\"pnks1111\"
    -lmbedtls
    -lmbedx509
    -lmbedcrypto

lib_deps =
    UIPEthernet
    https://github.com/ChuckBell/MySQL_Connector_Arduino
    bblanchon/ArduinoJson
