//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RFID.Utility.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RFID.Utility.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 EPC(Q) 的當地語系化字串。
        /// </summary>
        public static string B02GroupQButton {
            get {
                return ResourceManager.GetString("B02GroupQButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Log 的當地語系化字串。
        /// </summary>
        public static string B02GroupRecordLog {
            get {
                return ResourceManager.GetString("B02GroupRecordLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Multi(U) 的當地語系化字串。
        /// </summary>
        public static string B02GroupUButton {
            get {
                return ResourceManager.GetString("B02GroupUButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Basic 的當地語系化字串。
        /// </summary>
        public static string B02Item01 {
            get {
                return ResourceManager.GetString("B02Item01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Customize 的當地語系化字串。
        /// </summary>
        public static string B02Item02 {
            get {
                return ResourceManager.GetString("B02Item02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cycle-Index: 的當地語系化字串。
        /// </summary>
        public static string B04AntennaCycleIndex {
            get {
                return ResourceManager.GetString("B04AntennaCycleIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Execution: 的當地語系化字串。
        /// </summary>
        public static string B04AntennaExecution {
            get {
                return ResourceManager.GetString("B04AntennaExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Repeat Execution Interval(s): 的當地語系化字串。
        /// </summary>
        public static string B04AntennaRepeatExecutionInterval {
            get {
                return ResourceManager.GetString("B04AntennaRepeatExecutionInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Repeated 的當地語系化字串。
        /// </summary>
        public static string B04AntennaRepeatRun {
            get {
                return ResourceManager.GetString("B04AntennaRepeatRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Run 的當地語系化字串。
        /// </summary>
        public static string B04AntennaRun {
            get {
                return ResourceManager.GetString("B04AntennaRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Antenna Select: 的當地語系化字串。
        /// </summary>
        public static string B04AntennaSelect {
            get {
                return ResourceManager.GetString("B04AntennaSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Stop 的當地語系化字串。
        /// </summary>
        public static string B04AntennaStop {
            get {
                return ResourceManager.GetString("B04AntennaStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Antenna Type: 的當地語系化字串。
        /// </summary>
        public static string B04AntennaType {
            get {
                return ResourceManager.GetString("B04AntennaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Tag Count: 的當地語系化字串。
        /// </summary>
        public static string B04TagCountTitle {
            get {
                return ResourceManager.GetString("B04TagCountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Read Count: 的當地語系化字串。
        /// </summary>
        public static string B04TagReadCountTitle {
            get {
                return ResourceManager.GetString("B04TagReadCountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Basic Operator 的當地語系化字串。
        /// </summary>
        public static string Border01 {
            get {
                return ResourceManager.GetString("Border01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Multi Operator 的當地語系化字串。
        /// </summary>
        public static string Border02 {
            get {
                return ResourceManager.GetString("Border02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 EM demo 的當地語系化字串。
        /// </summary>
        public static string Border03 {
            get {
                return ResourceManager.GetString("Border03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Multi Antenna 的當地語系化字串。
        /// </summary>
        public static string Border04 {
            get {
                return ResourceManager.GetString("Border04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Customize 的當地語系化字串。
        /// </summary>
        public static string Border05 {
            get {
                return ResourceManager.GetString("Border05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Connect 的當地語系化字串。
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 BLE 的當地語系化字串。
        /// </summary>
        public static string ConnectBLE {
            get {
                return ResourceManager.GetString("ConnectBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 COM 的當地語系化字串。
        /// </summary>
        public static string ConnectCOM {
            get {
                return ResourceManager.GetString("ConnectCOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 NET 的當地語系化字串。
        /// </summary>
        public static string ConnectNet {
            get {
                return ResourceManager.GetString("ConnectNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 USB 的當地語系化字串。
        /// </summary>
        public static string ConnectUSB {
            get {
                return ResourceManager.GetString("ConnectUSB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Disconnect 的當地語系化字串。
        /// </summary>
        public static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Lock(L) 的當地語系化字串。
        /// </summary>
        public static string EditCommandL {
            get {
                return ResourceManager.GetString("EditCommandL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Access(P) 的當地語系化字串。
        /// </summary>
        public static string EditCommandP {
            get {
                return ResourceManager.GetString("EditCommandP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Read(R) 的當地語系化字串。
        /// </summary>
        public static string EditCommandR {
            get {
                return ResourceManager.GetString("EditCommandR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Select(T) 的當地語系化字串。
        /// </summary>
        public static string EditCommandT {
            get {
                return ResourceManager.GetString("EditCommandT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 MultiRead(UR)/SingleRead(QR) 的當地語系化字串。
        /// </summary>
        public static string EditCommandUQR {
            get {
                return ResourceManager.GetString("EditCommandUQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Write(W) 的當地語系化字串。
        /// </summary>
        public static string EditCommandW {
            get {
                return ResourceManager.GetString("EditCommandW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Q/U 的當地語系化字串。
        /// </summary>
        public static string Group_EPC_MultiRead {
            get {
                return ResourceManager.GetString("Group_EPC_MultiRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Read U 的當地語系化字串。
        /// </summary>
        public static string Group_EPC_Read_U {
            get {
                return ResourceManager.GetString("Group_EPC_Read_U", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 EPC (U) 的當地語系化字串。
        /// </summary>
        public static string Group_EPC_ReadEPC_U {
            get {
                return ResourceManager.GetString("Group_EPC_ReadEPC_U", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cont. 的當地語系化字串。
        /// </summary>
        public static string Group_EPC_RepeartRead {
            get {
                return ResourceManager.GetString("Group_EPC_RepeartRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Repeat Interval 的當地語系化字串。
        /// </summary>
        public static string Group_EPC_RepeatInterval {
            get {
                return ResourceManager.GetString("Group_EPC_RepeatInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 GPIO 的當地語系化字串。
        /// </summary>
        public static string Group_GPIO {
            get {
                return ResourceManager.GetString("Group_GPIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Read 的當地語系化字串。
        /// </summary>
        public static string Group_GPIO_Read {
            get {
                return ResourceManager.GetString("Group_GPIO_Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Kill 的當地語系化字串。
        /// </summary>
        public static string Group_Kill {
            get {
                return ResourceManager.GetString("Group_Kill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Kill 的當地語系化字串。
        /// </summary>
        public static string Group_Kill_Kill {
            get {
                return ResourceManager.GetString("Group_Kill_Kill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Kill pwd 的當地語系化字串。
        /// </summary>
        public static string Group_Kill_KillPwd {
            get {
                return ResourceManager.GetString("Group_Kill_KillPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Lock 的當地語系化字串。
        /// </summary>
        public static string Group_Lock {
            get {
                return ResourceManager.GetString("Group_Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Action 的當地語系化字串。
        /// </summary>
        public static string Group_Lock_Action {
            get {
                return ResourceManager.GetString("Group_Lock_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Action: 的當地語系化字串。
        /// </summary>
        public static string Group_Lock_Action_Field {
            get {
                return ResourceManager.GetString("Group_Lock_Action_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Lock 的當地語系化字串。
        /// </summary>
        public static string Group_Lock_Action_Lock {
            get {
                return ResourceManager.GetString("Group_Lock_Action_Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 PermaLock 的當地語系化字串。
        /// </summary>
        public static string Group_Lock_Action_PermaLock {
            get {
                return ResourceManager.GetString("Group_Lock_Action_PermaLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Un-Lock 的當地語系化字串。
        /// </summary>
        public static string Group_Lock_Action_unLock {
            get {
                return ResourceManager.GetString("Group_Lock_Action_unLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Un-PermaLock 的當地語系化字串。
        /// </summary>
        public static string Group_Lock_Action_unPermaLock {
            get {
                return ResourceManager.GetString("Group_Lock_Action_unPermaLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Lock 的當地語系化字串。
        /// </summary>
        public static string Group_Lock_Execute {
            get {
                return ResourceManager.GetString("Group_Lock_Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Mask/Action Field: 的當地語系化字串。
        /// </summary>
        public static string Group_Lock_Field {
            get {
                return ResourceManager.GetString("Group_Lock_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 / 的當地語系化字串。
        /// </summary>
        public static string Group_Lock_Field_ {
            get {
                return ResourceManager.GetString("Group_Lock_Field_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Access pwd 的當地語系化字串。
        /// </summary>
        public static string Group_Lock_Field_AccessPwd {
            get {
                return ResourceManager.GetString("Group_Lock_Field_AccessPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 EPC bank 的當地語系化字串。
        /// </summary>
        public static string Group_Lock_Field_EPC {
            get {
                return ResourceManager.GetString("Group_Lock_Field_EPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Kill pwd 的當地語系化字串。
        /// </summary>
        public static string Group_Lock_Field_KillPwd {
            get {
                return ResourceManager.GetString("Group_Lock_Field_KillPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 TID bank 的當地語系化字串。
        /// </summary>
        public static string Group_Lock_Field_TID {
            get {
                return ResourceManager.GetString("Group_Lock_Field_TID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 USER bank 的當地語系化字串。
        /// </summary>
        public static string Group_Lock_Field_USER {
            get {
                return ResourceManager.GetString("Group_Lock_Field_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Mask: 的當地語系化字串。
        /// </summary>
        public static string Group_Lock_Mask_Field {
            get {
                return ResourceManager.GetString("Group_Lock_Mask_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Mag: 的當地語系化字串。
        /// </summary>
        public static string Group_Msg {
            get {
                return ResourceManager.GetString("Group_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Send 的當地語系化字串。
        /// </summary>
        public static string Group_Msg_ButtonCustom {
            get {
                return ResourceManager.GetString("Group_Msg_ButtonCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ID: 的當地語系化字串。
        /// </summary>
        public static string Group_Msg_ID {
            get {
                return ResourceManager.GetString("Group_Msg_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Status: 的當地語系化字串。
        /// </summary>
        public static string Group_Msg_Status {
            get {
                return ResourceManager.GetString("Group_Msg_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Ver: 的當地語系化字串。
        /// </summary>
        public static string Group_Msg_Ver {
            get {
                return ResourceManager.GetString("Group_Msg_Ver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Pre-Setting Command 的當地語系化字串。
        /// </summary>
        public static string Group_PreSet {
            get {
                return ResourceManager.GetString("Group_PreSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Set Access(P) to pre-command 的當地語系化字串。
        /// </summary>
        public static string Group_PreSet_Access {
            get {
                return ResourceManager.GetString("Group_PreSet_Access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Access Password: 的當地語系化字串。
        /// </summary>
        public static string Group_PreSet_AccessPassword {
            get {
                return ResourceManager.GetString("Group_PreSet_AccessPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Set Select(T) to pre-command  的當地語系化字串。
        /// </summary>
        public static string Group_PreSet_Select {
            get {
                return ResourceManager.GetString("Group_PreSet_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Address(bit): 的當地語系化字串。
        /// </summary>
        public static string Group_PreSet_Select_Address {
            get {
                return ResourceManager.GetString("Group_PreSet_Select_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Memory Bank: 的當地語系化字串。
        /// </summary>
        public static string Group_PreSet_Select_Bank {
            get {
                return ResourceManager.GetString("Group_PreSet_Select_Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Data: 的當地語系化字串。
        /// </summary>
        public static string Group_PreSet_Select_Data {
            get {
                return ResourceManager.GetString("Group_PreSet_Select_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Length(bit): 的當地語系化字串。
        /// </summary>
        public static string Group_PreSet_Select_Length {
            get {
                return ResourceManager.GetString("Group_PreSet_Select_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 EPC(Q) Command 的當地語系化字串。
        /// </summary>
        public static string Group_Q {
            get {
                return ResourceManager.GetString("Group_Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 with Read Control 的當地語系化字串。
        /// </summary>
        public static string Group_ReadCtrl {
            get {
                return ResourceManager.GetString("Group_ReadCtrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Read/Write 的當地語系化字串。
        /// </summary>
        public static string Group_ReadWrite {
            get {
                return ResourceManager.GetString("Group_ReadWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Address: 的當地語系化字串。
        /// </summary>
        public static string Group_ReadWrite_Address {
            get {
                return ResourceManager.GetString("Group_ReadWrite_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Memory Bank: 的當地語系化字串。
        /// </summary>
        public static string Group_ReadWrite_Bank {
            get {
                return ResourceManager.GetString("Group_ReadWrite_Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Data: 的當地語系化字串。
        /// </summary>
        public static string Group_ReadWrite_Data {
            get {
                return ResourceManager.GetString("Group_ReadWrite_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Length(word): 的當地語系化字串。
        /// </summary>
        public static string Group_ReadWrite_Length {
            get {
                return ResourceManager.GetString("Group_ReadWrite_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Read 的當地語系化字串。
        /// </summary>
        public static string Group_ReadWrite_Read {
            get {
                return ResourceManager.GetString("Group_ReadWrite_Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Write 的當地語系化字串。
        /// </summary>
        public static string Group_ReadWrite_Write {
            get {
                return ResourceManager.GetString("Group_ReadWrite_Write", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Tag Record 的當地語系化字串。
        /// </summary>
        public static string Group_Record {
            get {
                return ResourceManager.GetString("Group_Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Clear 的當地語系化字串。
        /// </summary>
        public static string Group_Record_Clear {
            get {
                return ResourceManager.GetString("Group_Record_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Tag Count : 的當地語系化字串。
        /// </summary>
        public static string Group_Record_Count {
            get {
                return ResourceManager.GetString("Group_Record_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Info 的當地語系化字串。
        /// </summary>
        public static string Group_Record_Info {
            get {
                return ResourceManager.GetString("Group_Record_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Run Count: 的當地語系化字串。
        /// </summary>
        public static string Group_Record_RunCount {
            get {
                return ResourceManager.GetString("Group_Record_RunCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Read Count: 的當地語系化字串。
        /// </summary>
        public static string Group_Record_TagCount {
            get {
                return ResourceManager.GetString("Group_Record_TagCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Tags per Second: 的當地語系化字串。
        /// </summary>
        public static string Group_Record_TimeAvgCount {
            get {
                return ResourceManager.GetString("Group_Record_TimeAvgCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Reader Setting 的當地語系化字串。
        /// </summary>
        public static string Group_Setting {
            get {
                return ResourceManager.GetString("Group_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Adjust 的當地語系化字串。
        /// </summary>
        public static string Group_Setting_Adjust {
            get {
                return ResourceManager.GetString("Group_Setting_Adjust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Adjust frequency : +/- 30.5Hz intervals * n step 的當地語系化字串。
        /// </summary>
        public static string Group_Setting_Adjust_Frequency {
            get {
                return ResourceManager.GetString("Group_Setting_Adjust_Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Area 的當地語系化字串。
        /// </summary>
        public static string Group_Setting_Area {
            get {
                return ResourceManager.GetString("Group_Setting_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Base-band 的當地語系化字串。
        /// </summary>
        public static string Group_Setting_Baseband {
            get {
                return ResourceManager.GetString("Group_Setting_Baseband", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Baseband Mode : 的當地語系化字串。
        /// </summary>
        public static string Group_Setting_Baseband_Mode {
            get {
                return ResourceManager.GetString("Group_Setting_Baseband_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Carry 的當地語系化字串。
        /// </summary>
        public static string Group_Setting_Baseband_Mode_Carry {
            get {
                return ResourceManager.GetString("Group_Setting_Baseband_Mode_Carry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 RX 的當地語系化字串。
        /// </summary>
        public static string Group_Setting_Baseband_Mode_RX {
            get {
                return ResourceManager.GetString("Group_Setting_Baseband_Mode_RX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Baud Rate 的當地語系化字串。
        /// </summary>
        public static string Group_Setting_BaudRate {
            get {
                return ResourceManager.GetString("Group_Setting_BaudRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Measure 的當地語系化字串。
        /// </summary>
        public static string Group_Setting_Measure {
            get {
                return ResourceManager.GetString("Group_Setting_Measure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Measure Frequency 的當地語系化字串。
        /// </summary>
        public static string Group_Setting_Measure_Frequency {
            get {
                return ResourceManager.GetString("Group_Setting_Measure_Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Input freq. (MHz) : 的當地語系化字串。
        /// </summary>
        public static string Group_Setting_Measure_Input {
            get {
                return ResourceManager.GetString("Group_Setting_Measure_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Power 的當地語系化字串。
        /// </summary>
        public static string Group_Setting_Power {
            get {
                return ResourceManager.GetString("Group_Setting_Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Regulation 的當地語系化字串。
        /// </summary>
        public static string Group_Setting_Regulation {
            get {
                return ResourceManager.GetString("Group_Setting_Regulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Reset 的當地語系化字串。
        /// </summary>
        public static string Group_Setting_Reset {
            get {
                return ResourceManager.GetString("Group_Setting_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Run 的當地語系化字串。
        /// </summary>
        public static string Group_Setting_Run {
            get {
                return ResourceManager.GetString("Group_Setting_Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Set 的當地語系化字串。
        /// </summary>
        public static string Group_Setting_Set {
            get {
                return ResourceManager.GetString("Group_Setting_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Tag Test 的當地語系化字串。
        /// </summary>
        public static string Group_Setting_TagTest {
            get {
                return ResourceManager.GetString("Group_Setting_TagTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Status 的當地語系化字串。
        /// </summary>
        public static string Group_Status {
            get {
                return ResourceManager.GetString("Group_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Area : 的當地語系化字串。
        /// </summary>
        public static string Group_Status_Area {
            get {
                return ResourceManager.GetString("Group_Status_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Frequency : 的當地語系化字串。
        /// </summary>
        public static string Group_Status_Frequency {
            get {
                return ResourceManager.GetString("Group_Status_Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Offset : 的當地語系化字串。
        /// </summary>
        public static string Group_Status_Offset {
            get {
                return ResourceManager.GetString("Group_Status_Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Power : 的當地語系化字串。
        /// </summary>
        public static string Group_Status_Power {
            get {
                return ResourceManager.GetString("Group_Status_Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Update 的當地語系化字串。
        /// </summary>
        public static string Group_Status_Update {
            get {
                return ResourceManager.GetString("Group_Status_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Tag List: 的當地語系化字串。
        /// </summary>
        public static string Group_TagWindow {
            get {
                return ResourceManager.GetString("Group_TagWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Get Tag 的當地語系化字串。
        /// </summary>
        public static string Group_TagWindow_Get {
            get {
                return ResourceManager.GetString("Group_TagWindow_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Test 的當地語系化字串。
        /// </summary>
        public static string Group_TagWindow_Run {
            get {
                return ResourceManager.GetString("Group_TagWindow_Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Multi(U) Command 的當地語系化字串。
        /// </summary>
        public static string Group_U {
            get {
                return ResourceManager.GetString("Group_U", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Slot Q: 的當地語系化字串。
        /// </summary>
        public static string Group_U_SlotQ {
            get {
                return ResourceManager.GetString("Group_U_SlotQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Slot Q 的當地語系化字串。
        /// </summary>
        public static string Group_U_SlotQ1 {
            get {
                return ResourceManager.GetString("Group_U_SlotQ1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 EPC/TID  的當地語系化字串。
        /// </summary>
        public static string GroupEPC {
            get {
                return ResourceManager.GetString("GroupEPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 EPC 的當地語系化字串。
        /// </summary>
        public static string GroupEPCReadEPC {
            get {
                return ResourceManager.GetString("GroupEPCReadEPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 TID 的當地語系化字串。
        /// </summary>
        public static string GroupEPCReadTID {
            get {
                return ResourceManager.GetString("GroupEPCReadTID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 0:Readable and writeable 的當地語系化字串。
        /// </summary>
        public static string Lock_00Description {
            get {
                return ResourceManager.GetString("Lock_00Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 0:Writeable 的當地語系化字串。
        /// </summary>
        public static string Lock_00Description_ {
            get {
                return ResourceManager.GetString("Lock_00Description_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 1:Permanently readable and writeable 的當地語系化字串。
        /// </summary>
        public static string Lock_01Description {
            get {
                return ResourceManager.GetString("Lock_01Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 1:Permanently writeable 的當地語系化字串。
        /// </summary>
        public static string Lock_01Description_ {
            get {
                return ResourceManager.GetString("Lock_01Description_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 2:Pwd is not zero, readable and writeable protected 的當地語系化字串。
        /// </summary>
        public static string Lock_10Description {
            get {
                return ResourceManager.GetString("Lock_10Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 2:Pwd is not zero, writeable protected 的當地語系化字串。
        /// </summary>
        public static string Lock_10Description_ {
            get {
                return ResourceManager.GetString("Lock_10Description_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 3:Pwd is not zero, permanently readable and writeable protected 的當地語系化字串。
        /// </summary>
        public static string Lock_11Description {
            get {
                return ResourceManager.GetString("Lock_11Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 3:Pwd is not zero, permanently writeable protected 的當地語系化字串。
        /// </summary>
        public static string Lock_11Description_ {
            get {
                return ResourceManager.GetString("Lock_11Description_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Regulation information 的當地語系化字串。
        /// </summary>
        public static string MessageBox_Option {
            get {
                return ResourceManager.GetString("MessageBox_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Device Disconnected 的當地語系化字串。
        /// </summary>
        public static string MSG_DeviceDisconnected {
            get {
                return ResourceManager.GetString("MSG_DeviceDisconnected", resourceCulture);
            }
        }
    }
}
