[platformio]
default_envs = esp02s

[common]
custom_server_upload_dir = C:/WS/vs_kdh/pnk_kdh/자체제작OTA 대시보드 서버/uploads
custom_output_basename = esp02s_custom.bin
custom_remote_ota_host = gym907-0001.iptime.org
custom_remote_ota_port = 23
custom_remote_ota_user = dockeruser
custom_remote_ota_password = cyz5sXpqvJna
custom_remote_ota_dir = /home/pnkslabserver/tasmota-firmware
custom_remote_ota_subdir = esp02s/custom
custom_remote_ota_link_script = /home/pnkslabserver/tasmota-firmware/common/update_latest_links.py
custom_swagger_base_url = http://gym907-0001.iptime.org:3315
custom_swagger_enable = 1
custom_swagger_user = admin
custom_swagger_password = admin1234
custom_swagger_project_id = 10
custom_swagger_chip_type = esp02s
custom_swagger_firmware_family = custom


[env:esp02s]
platform = espressif8266@4.2.1
board = esp8285
framework = arduino

monitor_speed = 115200
board_build.flash_mode = dout
board_build.ldscript = eagle.flash.1m.ld
board_build.filesystem = none
build_flags =
    -DESP8266_1M

extra_scripts =
    pre:pio-tools/set-code-image.py
    post:pio-tools/post-firmware-copy.py

lib_deps =
    arduino-libraries/NTPClient @ ^3.2.1
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^6.21.3
    tzapu/WiFiManager @ ^2.0.17
